# Generated by Django 2.2.19 on 2022-10-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='의사명')),
                ('hospital', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='병원이름')),
                ('nonpay', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='비급여진료과목')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_monday', models.BooleanField(default=False, verbose_name='월요일')),
                ('task_tuesday', models.BooleanField(default=False, verbose_name='화요일')),
                ('task_wednesday', models.BooleanField(default=False, verbose_name='수요일')),
                ('task_thursday', models.BooleanField(default=False, verbose_name='목요일')),
                ('task_friday', models.BooleanField(default=False, verbose_name='금요일')),
                ('task_saturday', models.BooleanField(default=False, verbose_name='토요일')),
                ('task_sunday', models.BooleanField(default=False, verbose_name='일요일')),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Weekly_Task', to='doctor.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='LunchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lunch_Task', to='doctor.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DepertmentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='진료과1')),
                ('department2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='진료과2')),
                ('department3', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='진료과3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_Depertment', to='doctor.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_dt', models.DateTimeField()),
                ('agree_status', models.BooleanField(default=False, verbose_name='응답상태')),
                ('degree_time', models.BooleanField(default=False, verbose_name='거절상태')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Treatment_Doctor', to='doctor.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appliy_Patient', to='patient.Patient')),
            ],
        ),
    ]
